### ISSUE TITLE
con filename reserved in windows

### ISSUE THREAD

**Issue by 0x433** [kiffie/pic32-pac#1]
**Expected Behavior**

git clone https://github.com/kiffie/pic32-pac works on windows

**Actual Behavior**

error: unable to stat just-written file pic32mx2xxfxxxb/src/spi1/con.rs: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Steps to Reproduce the Problem**

On a windows machine with git configured
git clone https://github.com/kiffie/pic32-pac

It seems files named con are reserved and this code base contains 9 entries.

Thanks for the great work though!

**Comment by kiffie** [comment]
That's really annoying. I did not yet try it under Windows and thus was not aware of this problem.

I tend to rename the CON registers to CONT (for control) and to CON1 for peripherals that have a CON2 register.

The changes are in the repo under the `win_res_names` branch. I managed to check the files out under Windows.

**Comment by 0x433** [comment]
I agree that this is very annoying. I confirm, the `win_res_names` branch was checked out on Windows without errors. I am very excited about the prospect of using Rust for pic32! Thank you!

**Comment by kiffie** [comment]
In the meantime, I adapted the HAL modules. The _blinky_ example now compiles nicely under Windows. I even flashed it and it works :-)

BTW, I forgot to mention the components _rust-src_ and _llvm-tools-preview_ in the README.md file.

Thanks a lot for having reported this issue. I simply did not try it under Windows.

**Comment by 0x433** [comment]
Thank you! 👍 In fact, at this time I was doing the same thing - making changes to `pic32-hal` to make the `blinky` work :) But I was ashamed to send a pull request as I had never done it before. Now I confirm, your `blinky` work under my Windows!
I plan to add support for at least one pic32mk in order to try you project on the hardware I have. I can't say that I have a lot of experience and time to do this, but if I achieve a positive result, I will be happy to add it to your project. Also, I am interested in the pic32 official support in the Rust and I will be glad if I can somehow speed it up.

**Comment by kiffie** [comment]
I would be happy to add your PIC32MK related code. I actually started this project because I could not find any support for the PIC32 in Rust. To start with the PIC32MK, it may make sense to start with the PAC (to be generated from the manufacturer's XML (.PIC) file) and with core support and startup code.
