### ISSUE TITLE
svd2rust version

### ISSUE THREAD

**Issue by 0x433** [kiffie/pic32-pac#2]
I have made some progress with the addition of a new MCU to `pic32-pac`. But I found that it's looks like the current version of `svd2rust`  0.17.0 (73d42ff 2020-08-30) gives slightly different output in `pic32-pac` project. Which version of  `svd2rust` did you use?

**Comment by kiffie** [comment]
output of `svd2rust --version` is
`svd2rust 0.17.0 ( )`
